FROM python:3.8-buster

WORKDIR /app

COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install pip --upgrade && python -m pip install -r /tmp/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]
